# Copyright (c) 2020 Huawei Technologies Co., Ltd.
# Licensed under CC BY-NC-SA 4.0 (Attribution-NonCommercial-ShareAlike 4.0 International) (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
#
# The code is released for academic research use only. For commercial use, please contact Huawei Technologies Co., Ltd.
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file contains content licensed by https://github.com/xinntao/BasicSR/blob/master/LICENSE/LICENSE

#### general settings
name: pre_merge
use_tb_logger: true
model: TSFLOWMERGE  
distortion: sr
scale: 4
gpu_ids: [ 0 ]

datasets:
  train:
    name: EXPERTC
    mode: EXPERTC
    dataroot_GT: /home/oem/Tasks/Datasets/Starenhancer/train/03-Experts-C
    dataroot_LQ: /home/oem/Tasks/Datasets/Starenhancer/train/06-Input-ExpertC1.5
    quant: 32
    data: 'raise'
    use_shuffle: true
    n_workers: 2  # per GPU
    batch_size: 8
    GT_size: 256
    use_flip: true
    color: RGB
    local: False

  val:
    name: EXPERTC
    mode: EXPERTC
    dataroot_GT: /home/oem/Tasks/Datasets/Starenhancer/train/03-Experts-C
    dataroot_LQ: /home/oem/Tasks/Datasets/Starenhancer/train/06-Input-ExpertC1.5
    quant: 32
    n_max: 20
    local: False

  test:
    name: EXPERTC
    mode: EXPERTC
    dataroot_GT: /home/oem/Tasks/Datasets/Starenhancer/test/03-Experts-C
    dataroot_LQ: /home/oem/Tasks/Datasets/Starenhancer/test/06-Input-ExpertC1.5
    quant: 32
    n_max: 20
    local: False
#### Test Settings
dataroot_GT: ../datasets/div2k-validation-modcrop8-gt
dataroot_LR: ../datasets/div2k-validation-modcrop8-x4
model_path: ../experiments/pre_merge/models/1415500_G.pth


heat: 0.8 # This is the standard deviation of the latent vectors

#### network structures
network_G:
  which_model_G: TSFlowMergeNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
  upscale: 4
  train_RRDB: true
  train_RRDB_delay: 0.5

  flow:
    K: 8
    L: 1
    noInitialInj: true
    coupling: CondAffineSeparatedAndCond
    additionalFlowNoAffine: 2
    split:
      enable: true
    fea_up0: true
    stackRRDB:
      blocks: [ 1, 8, 15, 22 ]
      concat: true

#### path
path:
  pretrain_model_G: 
  strict_load: True
  resume_state: auto

#### training settings: learning rate scheme, loss
train:
  manual_seed: 10
  lr_G: !!float 4e-5
  weight_decay_G: 0
  beta1: 0.9
  beta2: 0.99
  lr_scheme: MultiStepLR
  warmup_iter: -1  # no warm up
  lr_steps_rel: [ 0.5, 0.75, 0.9, 0.95 ]
  lr_gamma: 0.5

  niter: 10200000
  val_freq: 40000

#### validation settings
val:
  heats: [ 0.0, 0.5, 0.75, 1.0 ]
  n_sample: 3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
